* Finance

Estate finances are in good shape and we have reserves to enable the estate to run for at least six months if all payments were suddenly to stop. That is why we maintain a reserve. The money we have in reserve is held in a fixed deposit, which, even though we have to pay taxes on it's gains, grows and keeps members' money working while it sits in reserve.

We are looking at beefing up the guards co-operative holdings with a view to being able to help them sort out legal cases, like the one we recently had to help them fight, out of their own funds should the need arise. The Co-op holdings at present only amount to approximately KSh. 170,000. Any court case would of course consume much more than that.

Kirit Shah and Geoffrey Naituli continue to maintain the accounts in exemplary condition with our office manager Karanja entering the data into our accounting system. Within a few months we will once again be sending off these figures to our auditors to have them look over our handywork to approve it for final presentation at the Annual General Meeting and then to adopt it into the running of NRWS.

There are still a few members who freebie off the goodwill of others and we ask that you don't to this but do bring your dues up to current. If you are a resident that knows of such members we request that you approach them and let them know that the security we enjoy in Nyari (Nyari is considered the safest estate to live in in Nairobi), the street lighting, the internet access, the roads, the environment and much, much more all comes about as a result of the harambee effort of all members whose contributions are put to good effect through the committee.

* Security

We spent a peaceful and uneventful holiday season on the security front. We have the Security Subcommittee to thank for this. Their vigilance continues to pay dividends. It behooves all of us to continue to watch our neighbourhood carefully. If you see anything suspicious please do report your concerns to the Nyari office. There are several on-going construction projects within the estate and these sites have, in the past, been found to be the source from where thugs come. The days the staff on those sites are paid are particularly troublesome. If you are running a construction project we urge you to stagger your payment days and not let anyone know that you are going to be bringing money on site. Today we have MPesa and AirTel Money and if you can pay all or the majority of your staff through those modalities then so much the better. 

We recount a story we've just heard. In a neighbouring residential area a homeowner headed into her house at 8pm one evening after a long slog through the traffic of industrial area. Using her remote gate opener she opened her gate then closed it behind her. As she alighted from her car a thug carrying a large gun (from the description - an AK47), accosted her and threatened to harm her if she did not cooperate. A second thug pointed a handgun at her. The two then proceeded to bundle her onto the back seat of her car and drove off after they used her remote to open the gate. Her husband had been in the house at the time and had seen what happened. He alerted his residential association security people who promptly contacted the police who in turn started circulating the car number. The thugs did not go very far. In the South 'C' part of Nairobi they dropped the woman unharmed and made off with the vehicle which was discovered a few kilometres from where the lady had been dropped. The interesting part of this story is this: All through her drive to South 'C' the owner of the car, sitting at gun-point on the back seat, listened to a radio with police speaking on it. She heard her car number mentioned several times but could not understand what the thugs were saying to each other. They were obviously much troubled by the radio chatter and she thinks they let her go so quickly and abandoned her car a short way away because of the prompt action her husband took and the circulaiton of the car number by the police.

This long story to point out some salient features of this robbery. First entering your house day or night is a vulnerable point in time. Be careful and watchful as you stand at the gate waiting for it to be opened and once you are inside your compound coming out of your car. If you see a vehicle approaching or sense the presence of poeple at or inside your gate it is more prudent to simply drive away make a round of the estate and come back. You may feel better if your alert the office as you pass by it. Secondly, don't resist; you can always buy another car, you can't easily get your health back once you are injured. In all robberies the perpetrators want to get away as quickly as possible. Don't get in their way. Give them what they want and let them go. Thirdly, prompt action by those around you can only work if you communicate what is going to your neighbourhood association as quickly as possible. In Nyari we are very fortunate to have a Police Post that we constructed all those years back and whose staff especially the new Senior Corporal Ochieng (+254 722 506042) is really on the ball and doing his job extremely well. The Police Post is one cog in a well-oiled machine the other parts being the numerous guards we have, the barriers, the radio and cell phone network and of course the security subcommittee members. The entire thing works as a smooth machine and is the primary reason the NRWS exists and for what you pay your monthly dues.

The security subcommittee is in the process of purchasing another two handsets to complement our current 'fleet.' We are looking for Motorola GP300 radios complete with new batteries and a carry case. If you have any information regarding where we can source these please contact the office urgently.

* ICT
** Internet in Nyari
Jamii Telecom (JTL) continues to impress. In terms of raw speed no one else seems to be able to beat them. Zuku impresses in their triple pay offer and if you need telephony and television then currently Zuku's offering is better than JTL's. However we have had many reports from members complaining about Zuku speeds dropping off at peak hours which seem to be the evenings from 5pm to 10pm - a time when many want to relax and surf the internet or to answer their personal emails.

For some triple play is not a necessity, raw internet speeds being more important. Several families only watch YouTube videos for their entertainment while others want the raw speed for their work. There are software developers residing within Nyari for whom 10MBps is critically important. These users appreciate JTL's dedicated individual account service. JTL speeds do not drop no matter what time of day it is and are truly as advertised -- a 10MBps line gives you 10MBps in both directions up and down.
** CCTV
To date our security oriented CCTV network has been on the internet system that JTL setup across Nyari. This was done so as to have access to the cameras given to certain members to monitor in their spare time. To date it does not appear that the members given this access are able to do much monitoring. There is a monthly charge for this service as it is connected to the internet through JTL. It has been decided that considering the lack of usage of the monitoring facility as well as the monthly charge it would be more produent to switch to a dedicated CCTV system based on a fibreoptic cable laid specially for this. This will necessitate a one-off payment to the installer for the purchase of the fibre and the labour required to install it. Once this is done there will be no recurring monthly expense.
** Nyari on the net
You are encouraged to visit our internet sites including the Nyari Facebook page which you can find at (**Nyari FB link here), and our website (**weblink here). The Facebook page sees a lot of acitivity as all our members postings also appear on it. This gives you a way to see what your fellow Nyari members are up to and to figure out if there might be synergies between you and them. Do pay the page a visit.

* Environment
The Chairman, Mr Ghassmi, who lives at the top end of the lake where there is a small lake that feeds into the main lake has reported that he has removed close to two lorry loads worth of silt that has been trickling into the small lake over the past 15 years since he moved into Nyari. He has continually removed this silt and worries that if not removed the small lake will disappear completely once it fills up.

The small lake is a integral part of the Nyari Lakes ecosystem. Wetlands are now understood to be crucial parts of our environment that must be looked after with maximum vigilance. In the past we have had to fend off developers that wanted to drain the main Nyari lake to make way for apartments and more recently when a developer downstream of the lake built almost on top of the outflow river. Nyari has a tile deed for the main lake that is held by a group of Nyari appointed trustees the entire Nyari membership being entrusted, through it's various committees, to look after the resource. In other parts of the country, and based on the latest laws, there is a mandatory 250m zone that must be left between a lake or river margin and any developments. There is also a nationwide requirement for a leave of 1Km between these margins and any roads. Of course this it not possible in the case of man made dams like the Nyari lake which were zoned and developed many decades ago. Indeed all the houses on the main lake have their beacons below water level so the question of creating a 'leave' is laughable the leave being beyond the SECOND rows of houses on any of the Nyari lakes. Also most of the lakeside construction was effected well before the new laws came into force and they are not retrospective as this would mean demolishing hundreds of homes and destroying many neighbourhoods. The security risks alone mean we cannot allow public access to residential water bodies. Remember how Dr Aggarwal was shot and left for dead in his house in 1999? Those thugs came from the water side of his property which was not fenced at the time his being one of the few houses in Nyari then. Today the country as a whole is governed by these new laws and construction around lakes not permitted without a leave of 250m. But this does not mean that we can rest and not look after the resources to our utmost. We are crushing our environment all around us all over this planet. It behooves us to look after this estate to our very best, if not for us then at least for those generations that come after us.

How could we 'lose' the lakes? Actually - it could happen very easily. Here are some example scenarios. Let's say a house starts to discharge effluent (it's overflowing septic tank) into the lake. Within a few days to weeks the water in the lake will become enriched with nutrients from the decay of the effluent that will be building up in the water. That nutrient rich medium will then support algal blooms. Those blooms in turn will place demands on the water oxygen and other levels. Starvation of oxygen will occur which will lead to death of other organisms such as the millions of microbes, crustaceans and the hundreds of fish, crayfish, snails and crabs that lived together in harmony while the rich medium was held in check. The 'death' of the water would then lead to putrification -- rotting. The lake would become smelly, develop strange colours and this might even progress to a putrid water source that no one can live near. There is the possibility that the area could be declared unsuitable for human habitation, made into a disaster zone and all of us forced to leave to live elsewhere. Has this happened before elsewhere? 
** TODO find internet source of this having happened. Cite Nairobi dam.

Here is another scenario that has unfolded right here in Nairobi: Imagine a well-intentioned person bringing in a nice looking floating plant with lovely small purple flowers, from his weekend holiday in Lake Naivasha. The plant - water hyacinth. Hyacinth grows, like all living systems, on an exponentially described curve. What does this mean? Bear with me -- a little simple math is needed here for you to really, really appreciate what exponential growth is. Suppose you have one shilling and it's Monday morning. Now advance the time to Tuesday and double what you have. That means you now have TWO shillings. Again advance the time to Wednesday and double what you have -- FOUR shillings. Thursday, EIGTH shillings and so on. Now before you look at the answer on the next line stop and think and answer this ... when do you think you'll have ONE THOUSAND (1,000) shillings?

Most people are shocked by the answer ... NEXT WEEK WEDNESDAY!

Yes that's correct - go try it out for yourself. 8 - Thursday, 16 - Friday, 32 -  Saturday, 64 - Sunday, 128 - Monday, 256 - Tuesday, 512 Wednesday, 1024 - Thursday. So sometime on Wednesday you passed the 1000 mark!

That's what happens with exponential growth and water hyacinth follows almost exactly that same progression doubling it's mass every 24 hours. Carry on the progression and in 30 days, starting with just ONE single plant on day ONE, you have -- wait for it -- 1 BILLION plants! So in one month our lake would be overrun. This happened to Nairobi Dam (near Wilson Airport) and we've never been able to recover from this. That is what, coupled with sewerage being dumped into the dam from the slum dwellers on the margins, made the hyacinth grow even faster. Today you can drive your car over the dam and even walk over it easily. So could this happen to our dams? Ofcourse it can. Let's think about this carefully and renew our vigilance every day that we live close to such beautiful water bodies.

* Maintenance

The road repair that you've been watching over the past weeks has brought many of our roads back to past glory. 1.5 million shillings was spent in the extensive repairs which are as yet to be completed. To complete we're going to need another million shillings. Members were very kind in making an extra donation, by way of a road levy of KSh. 10,000/-. To complete we are going to need an additional million shillings (there's the major part of Ibis Drive still to be done). **do we mention who - I think I heard a name mentioned in the meeting - Pamina? - provided the road repair at cost?

Surprisingly and a little dissapointingly some members approached our office manager offering to make their 10k contribution payment on condition that their personal slip roads to their houses be completed first before the main thorougfares. The case in point is a road that comes off the main Ibis Drive up near Barrier 2. That road is about 250m long. To tarmac that road in total will cost upwards of 2 million shillings for that road alone! Now as that is not a road coming off the main estate roads we can't expect to be able to carpet that surface.

On a happier note, a member cabro tiled her entire slip road at her own cost. She then asked if the Nyari Committee would facilitate the fitting and wiring of street lights on that road. This is the sort of member we want to help. She paid close to 2 million shillings to tile her slip road and we feel that it is then justified that the committee spend Ksh 30,000/- to fit three lamp posts, the lights and their wiring and to get it all connected up to City Council power. As we are the ones with the power and mandate to liaise with the City Council on this we are the right people to approach and when we have a member so willing to improve the estate for all of us like this, through her own pocket, we are happy to add our bit to the project. We need more members to come forward with such projects. Please consider what you can do for your estate.

* Lands and Utility
* Youth

Nyari Youth have their own dedicated Facebook page. You can find it here (**link). Our youth are active in ... 

* Social

The Social Subcommittee is busy working on a venue for the Nyari party. They envisage a Febuary or March date for the party and that it will be held at a hotel or restaurant to ease the logistics of holding such a gathering. To date Zen Gardens has made an offer of KSh. 3,500/- per person with a cash bar. This seems a little high and alternatives are being sought in the 2,000/- range. We are expecting 80 members to attend this party and it will be a great time to get together and make aquaintance of your neighbours. These social get-togethers are an important facet of living in Nyari and we hope that you will all make an effort to attend.

* AOB
